# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getPM1 <- function(u, data) {
    .Call(`_DurocherProjectionMedian_getPM1`, u, data)
}

getMedInd <- function(curr_col, med, even) {
    .Call(`_DurocherProjectionMedian_getMedInd`, curr_col, med, even)
}

getPM2 <- function(u, data) {
    .Call(`_DurocherProjectionMedian_getPM2`, u, data)
}

rcpparma_hello_world <- function() {
    .Call(`_DurocherProjectionMedian_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_DurocherProjectionMedian_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_DurocherProjectionMedian_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_DurocherProjectionMedian_rcpparma_bothproducts`, x)
}

